version: '3.8'

services:
  converter:
    build: .
    container_name: bdb_converter
    volumes:
      - ./berkeley_dbs:/output
    environment:
      PG_HOST: host.docker.internal   
      PG_PORT: 5432
      PG_DB: repbase
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_SCHEMA: main
